### ISSUE TITLE
Request object doesn't emit "state" event

### ISSUE THREAD

**Issue by lebedenko** [expandjs/xp-request#2]
"state" event is not emitted, so there's no "xp-request-state" event in xp-request component as well as state property doesn't change its value

**Comment by Pupix** [comment]
Most likely the state doesn't change because your request doesn't get sent, as specified in expandjs/xp-request#3

**Comment by Pupix** [comment]
This has been fixed in the latest (0.10.0). Redownload using bower and you should be all good.
