### ISSUE TITLE
no data is sent to the server

### ISSUE THREAD

**Issue by lebedenko** [expandjs/xp-request#3]
submit() method doesn't send data to server neither in request body for POST queries nor in query params for GET queries

**Comment by Pupix** [comment]
Hello!

Basically you are saying `xp-request` doesn't work at all, which seems rather strange. I just tested it and everything seems to be working. Could you post a chunk of code with your use case. 

This is my test case:

```
<xp-request id="request" method="post" url="http://localhost:3000/test?query=param></xp-request>
...
attached: function () {
    this.$.request.submit({hello: 'world'}) //sending the body
}
```

on server I receive:

body: `{"hello":"world"}`
query: `{ query: 'param' }`

Cheers.

**Comment by lebedenko** [comment]
Hello!
Check please my testing code below.

server side (nodejs + expressjs)

```
router.get('/test', function (req, res) {
  res.json({
    state: 'ok',
    url: req.originalUrl,
    query: req.query,
    body: req.body
  });
});

router.post('/test', function (req, res) {
  res.json({
    state: 'ok',
    url: req.originalUrl,
    query: req.query,
    body: req.body
  });
});
```

html:

```
<xp-request
      id="request"
      url="http://localhost:3000/test"
      content-type="application/json"
      on-xp-request-submit="_onSubmit"
      on-xp-request-error="_onError"
      on-xp-request-state="_onState"></xp-request>
```

js:

```
attached() {
      let request = this.$.request;

      request.method = 'get';
      request
        .submit({test: 'Hello World'}, (err, data) => {
          console.log('error: ', err);
          console.log('data: ', data);
        });

      request.method = 'post';
      request.url = '/test?q=some+search+string';
      request
        .submit({test: 'Hello World'}, (err, data) => {
          console.log('error: ', err);
          console.log('data: ', data);
        });

      request.url = '/wrong-url';
      request.header('X-Requested-With', 'XMLHttpRequest');
      request
        .submit({test: 'Hello World'})
        .catch(function (err) {
          console.log(err);
        });
    },
    _onSubmit(_, detail) {
      console.log('_onSubmit');
      console.log(detail.data);
    },
    _onError(_, err) {
      console.log('_onError');
      console.log(err);
    },
    _onState(_, detail) {
      console.log('_onState');
      console.log(detail);
    },
```

Check out please attached screenshot of chrome browser dev console
![scr](https://cloud.githubusercontent.com/assets/437715/11532469/aff89cf6-990c-11e5-862b-f61cd98cbc32.png)

So, there are few issues:
1 - in the first request no query params added to the url (but should be as documented)
2 - in the second request no POST body sent
3 - as you can see, the code above fires 'xp-request-submit' and 'xp-request-error' as it should, but 'xp-request-state' not fired at all

Cheers

**Comment by Pupix** [comment]
There seems to be a problem with the documentation on the website (the [class](http://expandjs.com/classes/xp-request)' documentation has been updated but the [component](http://expandjs.com/elements/xp-request)'s doc no).
1. GET doesn't send the request body as query string anymore.
2. To intercept the body you either need [bodyParser](http://stackoverflow.com/questions/11625519/how-to-access-the-request-body-when-posting-using-node-js-and-express) or [a middleware](http://stackoverflow.com/a/9920700) that does its job.
3. This is actually a bug, a patch for it will land later this week.

Cheers.

**Comment by lebedenko** [comment]
1. Does it mean that I cannot pass query params to xp-request and should construct query string myself?
2. Got it, thank you

**Comment by Pupix** [comment]
Yes. You could set the `url` before calling submit with:

``` js
'http://localhost:300/test?' + XP.toQueryString({param: value})
```

**Comment by Pupix** [comment]
The  'xp-request-state' bug has been fixed in the latest release.
